### ISSUE TITLE
Use of pem-jwk Seemingly unneeded

### ISSUE THREAD

**Issue by jonassmedegaard** [solid/oidc-op#14]
It seems that the module `pem-jwk` provides a subset of the functionality also provided by module `@trust/keyto` pulled in via `@trust/webcrypto`.

If my guess (based only on superficially reading the documentation of those modules!) is correct, then it seems codebase can be slimmed a bit by refactoring to not use both.

**Comment by dmitrizagidulin** [comment]
Huh, good catch. I dont think that package is even used anywhere. I suspect it was refactored out but not removed from package.json.

**Comment by jonassmedegaard** [comment]
Quoting Dmitri Zagidulin (2019-02-04 03:31:08)
> Huh, good catch. I dont think that package is even used anywhere. I suspect it was refactored out but not removed from package.json.

Ah, indeed, it is not used anywhere in the code.  That was easy :-)

 - Jonas

-- 
 * Jonas Smedegaard - idealist & Internet-arkitekt
 * Tlf.: +45 40843136  Website: http://dr.jones.dk/

 [x] quote me freely  [ ] ask before reusing  [ ] keep private

**Comment by dmitrizagidulin** [comment]
pem-jwk dep has now been removed, closing this.
