### ISSUE TITLE
TokenRequest does not load cnfKey

### ISSUE THREAD

**Issue by wrmack** [solid/oidc-op#15]
I am new to solid so I may have this wrong.

I am experimenting with an iOS app able to implement the functionality of the solid platform.  I am running solid-server locally.

I am struggling a bit with PoP tokens and have now completed quite extensive reading around this.

My understanding is a native app uses the authorisation code flow (as compared to browsers which use the implicit flow).  This means that tokens are issued in response to requests to the token endpoint.

TokenRequest passes to IDToken at one point which checks whether the request has a cnfKey.  Unlike AuthenticationRequest (which is used for granting tokens in the implicit flow) TokenRequest does not actually load the cnfKey into the request.  Therefore ID token will never find it.

I copied and pasted the relevant code from AuthenticationRequest (which loads the cnfKey) to TokenRequest and it works OK.  I receive an access token and an ID token with cnf embedded.

"This specification extends the functionality of the token endpoint"
https://tools.ietf.org/html/draft-ietf-oauth-pop-key-distribution-04

Or, when using authorisation flow, should the key request be contained in the request to the authorisation endpoint??  This seems a bit odd because that part of the flow is not actually a request for a token.

**Comment by dmitrizagidulin** [comment]
@wrmack Thanks for letting us know! I suspect this may be an oversight on our part (handling the confirmation key in the Auth Request but not the Token Request). 

Let me take a look through the code and get back to you on this.

**Comment by wrmack** [comment]
If it helps, I have placed my patched TokenRequest here:
<https://github.com/wrmack/oidc-op/blob/c33e794c2c210f3310d1be47ff4d4636999c2af4/src/handlers/TokenRequest.js>

This works for me.

**Comment by dmitrizagidulin** [comment]
@wrmack thanks! :) I'll pull that in.

**Comment by wrmack** [comment]
That was quick!
Remember I am a novice - you better check it!

**Comment by dmitrizagidulin** [comment]
Of course :) No worries.

**Comment by SimonShapiro** [comment]
@dmitrizagidulin I have been working with @wrmack and Michael Thornburgh and it would appear that this is still not fixed or there is something else wrong.  Can you confirm whether this issue was closed?

**Comment by dmitrizagidulin** [comment]
K, will look into it!!

**Comment by SimonShapiro** [comment]
Thanks.

**Comment by dmitrizagidulin** [comment]
Addressed in PR https://github.com/interop-alliance/oidc-op/pull/1.
