### ISSUE TITLE
relies on unstable project @trust/json-document

### ISSUE THREAD

**Issue by jonassmedegaard** [solid/oidc-op#17]
This project depends on https://github.com/anvilresearch/json-document which according to its authors is unfinished, unstable and likely unmaintained: https://github.com/anvilresearch/json-document/issues/21#issuecomment-530421966

**Comment by dmitrizagidulin** [comment]
@jonassmedegaard Thanks for bringing this up! I'll create a tracking issue for this, probably over at the Authentication Panel, so we can coordinate what to do about the json-document dependency in our various libs.

**Comment by dmitrizagidulin** [comment]
Addressed by PR #18, closing.
